import { ScrollView, StyleSheet, Text, View, Pressable } from 'react-native';
import { useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';

const topics = [
  ['Algebra', 'Equations, expressions & factorisation', '72%'],
  ['Geometry', 'Angles, shapes, area & volume', '48%'],
  ['Trigonometry', 'Ratios, identities & applications', '31%'],
  ['Statistics', 'Data, probability & distributions', '64%'],
];
export default function Learn() { const router=useRouter(); return <ScrollView contentInsetAdjustmentBehavior="automatic" style={s.page} contentContainerStyle={s.content}><Text style={s.kicker}>LEARN</Text><Text style={s.title}>Build your maths skills</Text><Text style={s.sub}>Pick a topic and continue where you left off.</Text><View style={s.search}><Ionicons name="search" size={19} color="#64748b"/><Text style={s.searchText}>Search topics, lessons...</Text></View>{topics.map(([name,desc,progress],i)=><Pressable key={name} style={s.topic} onPress={()=>router.push('/tests')}><View style={s.icon}><Ionicons name={i===0?'calculator-outline':i===1?'shapes-outline':i===2?'triangle-outline':'bar-chart-outline'} size={24} color="#2563eb"/></View><View style={s.info}><Text style={s.name}>{name}</Text><Text style={s.desc}>{desc}</Text><View style={s.track}><View style={[s.fill,{width:progress}]}/></View><Text style={s.progress}>{progress} complete</Text></View><Ionicons name="chevron-forward" size={20} color="#94a3b8"/></Pressable>)}<View style={s.recent}><Text style={s.recentTitle}>Continue learning</Text><Text style={s.lesson}>Quadratic Equations</Text><Text style={s.lessonSub}>Lesson 4 · Completing the square</Text><Pressable style={s.button} onPress={()=>router.push('/tests')}><Text style={s.buttonText}>Continue lesson</Text></Pressable></View></ScrollView> }
const s=StyleSheet.create({page:{flex:1,backgroundColor:'#f8fafc'},content:{padding:20,paddingBottom:40,gap:12},kicker:{fontSize:12,fontWeight:'900',letterSpacing:1.5,color:'#2563eb'},title:{fontSize:28,fontWeight:'900',color:'#0f172a'},sub:{color:'#64748b',marginBottom:8},search:{height:50,backgroundColor:'#fff',borderRadius:15,paddingHorizontal:15,flexDirection:'row',alignItems:'center',gap:10},searchText:{color:'#94a3b8'},topic:{backgroundColor:'#fff',borderRadius:18,padding:15,flexDirection:'row',alignItems:'center',gap:13},icon:{width:46,height:46,borderRadius:14,backgroundColor:'#eff6ff',alignItems:'center',justifyContent:'center'},info:{flex:1},name:{fontSize:17,fontWeight:'800',color:'#0f172a'},desc:{fontSize:12,color:'#64748b',marginTop:2},track:{height:6,backgroundColor:'#e2e8f0',borderRadius:4,marginTop:9},fill:{height:6,backgroundColor:'#2563eb',borderRadius:4},progress:{fontSize:10,color:'#64748b',marginTop:4},recent:{backgroundColor:'#172554',borderRadius:20,padding:19,marginTop:5},recentTitle:{color:'#bfdbfe',fontSize:11,fontWeight:'900',letterSpacing:1},lesson:{color:'#fff',fontSize:20,fontWeight:'800',marginTop:6},lessonSub:{color:'#cbd5e1',marginTop:3},button:{backgroundColor:'#fff',alignSelf:'flex-start',paddingHorizontal:15,paddingVertical:10,borderRadius:11,marginTop:14},buttonText:{color:'#172554',fontWeight:'800'}});