import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getFirestore, collection, setDoc, doc, getDocs, query, orderBy } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";


const firebaseConfig={apiKey:"AIzaSyDbV4R5qAD80pZ8KqTHIiHFkXwQsNwWGr0",authDomain:"mlgo-86f79.firebaseapp.com",projectId:"mlgo-86f79",storageBucket:"mlgo-86f79.firebasestorage.app",messagingSenderId:"166999251760",appId:"1:166999251760:web:63a3afbdfaf7d6b90346f5",measurementId:"G-JEC3PT5219"};
const app=initializeApp(firebaseConfig), db=getFirestore(app);
const questions=[
["Arrange the following numbers in ascending order: 1/8, 1/7, 1/4, 11/56, 17/56",["1/8, 1/7, 1/4, 11/56, 17/56","1/8, 1/7, 11/56, 1/4, 17/56","1/8, 11/56, 1/7, 1/4, 17/56","1/8, 1/7, 11/56, 17/56, 1/4"],1],
["Simplify: (2½ + ⅓ − 1¾) ÷ (½ + 1⅓ − 1¼)",["7/13","7/12","12/13","1 6/7"],3],
["Simplify: 11/8 × 11/7 − 6/5 ÷ 4/5",["269/280","1 11/269","37/56","1 9/32"],2],
["Ade received 3/5 of a sum of money, Nelly 1/3 of the remainder while Austin took the rest. If Austin's share is greater than Nelly's by ₦3,000, how much did Ade receive?",["₦12,500","₦2,000","₦4,000","₦13,500"],3],
["A man spent 1/4 of his monthly salary on rent, 2/5 on food and 1/6 on his children's education. What fraction of his salary is left?",["11/60","13/60","7/20","19/30"],0],
["The number 192039 was corrected to 192000 by a student. Which of the following can be the correct approximation of figures taken? I – nearest hundred; II – nearest thousand; III – 3 significant figures; IV – 4 significant figures",["I and II only","II and III only","III and IV only","I, II, III and IV"],3],
["A sales boy gave a change of ₦75.00 to a buyer instead of ₦80.00. Calculate his percentage error, correct to one decimal place.",["6.0%","6.2%","6.3%","6.6%"],2],
["A man made a table with a rectangular top of dimensions 36 cm by 44 cm instead of 37 cm by 41 cm. What is the percentage error in the perimeter of the table, correct to 1 decimal place?",["11.1%","10.8%","4.42%","2.6%"],3],
["The distance between two points is measured to be 3.62 km. If this is more than the actual distance and the percentage error is calculated to be 5%, what is the actual distance?",["3.18 km","3.45 km","8.62 km","3.50 km"],1],
["Correct 5.0962894 to three significant figures.",["5.96","5.10","5.09","5.02"],1]
];
const letters=["A","B","C","D"], root=document.querySelector("#app");

let currentUser=null;

function header(){return `<div class="hero"><h1>Math League</h1><p>September 2026 Competition</p></div>`}
function home(){root.innerHTML=`<div class="shell">${header()}<div class="topnav"><button class="secondary" id="adminBtn">Admin Dashboard</button></div><div class="card"><h2>Student Competition</h2><p>10 mathematics questions · One attempt only</p><div class="grid"><label>Full name<input id="name" type="text" autocomplete="name" required></label><label>WhatsApp number<input id="whatsapp" type="text" autocomplete="off" required></label></div><div id="msg"></div><div class="actions"><button id="start">Start Competition</button></div></div></div>`;document.querySelector("#start").onclick=start;document.querySelector("#adminBtn").onclick=adminLogin}
async function start(){const name=document.querySelector("#name").value.trim(), studentId=document.querySelector("#studentId").value.trim();if(!name||!studentId)return showMsg("Enter your full name and WhatsApp number.","error");try{currentUser=await signInAnonymously(auth);const studentKey=studentId.trim().toLowerCase().replace(/[^a-z0-9_-]/g,"_");if(localStorage.getItem("mathLeagueSubmitted:"+studentKey))return showMsg("This browser has already recorded an attempt for this student ID.","error");quiz(name,studentId,studentKey)}catch(e){showMsg("Unable to connect to the competition server. Check your internet connection and Firebase setup.","error")}}
function quiz(name,studentId,studentKey){root.innerHTML=`<div class="shell">${header()}<div class="card"><h2>${esc(name)}</h2><p class="muted">WhatsApp number: ${esc(studentId)} · You can submit only once.</p><form id="quiz">${questions.map((q,i)=>`<section class="question"><h3>${i+1}. ${esc(q[0])}</h3>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"> <b>${letters[j]}.</b> ${esc(o)}</label>`).join("")}</section>`).join("")}<div id="msg"></div><div class="actions"><button type="submit">Submit Final Answers</button></div></form></div></div>`;document.querySelector("#quiz").onsubmit=e=>submit(e,name,studentId,studentKey)}
async function submit(e,name,studentId,studentKey){e.preventDefault();if(!confirm("Submit your answers? You cannot attempt the competition again after submission."))return;const fd=new FormData(e.target),answers=questions.map((_,i)=>fd.get("q"+i));if(answers.some(x=>x===null))return showMsg("Answer all 10 questions before submitting.","error");const score=answers.reduce((s,a,i)=>s+(Number(a)===questions[i][2]?1:0),0);try{await setDoc(doc(db,"submissions",studentKey),{name,studentId,studentKey,answers:answers.map(Number),score,percentage:score*10,submittedAt:new Date().toISOString(),uid:currentUser?.user?.uid||null});localStorage.setItem("mathLeagueSubmitted:"+studentKey,"1");result(name,score)}catch(err){showMsg("Submission failed. Your answers were not recorded. Please do not close the page; try again.","error")}}
function result(name,score){root.innerHTML=`<div class="shell">${header()}<div class="card"><div class="success"><h2>Competition submitted successfully</h2><p>Thank you, ${esc(name)}.</p></div><p class="score">${score}/10</p><p>You scored <b>${score*10}%</b>.</p><p class="muted">Your attempt has been recorded.</p></div></div>`}
function adminLogin(){root.innerHTML=`<div class="shell">${header()}<div class="card"><h2>Admin Dashboard</h2><p class="muted">Password required.</p><input id="pw" type="password" placeholder="Password" autocomplete="current-password"><div id="msg"></div><div class="actions"><button id="login">Sign in</button><button class="secondary" id="back">Back</button></div></div></div>`;document.querySelector("#login").onclick=()=>{if(document.querySelector("#pw").value==="faithful")admin();else showMsg("Incorrect password.","error")};document.querySelector("#back").onclick=home}
async function admin(){root.innerHTML=`<div class="shell">${header()}<div class="card"><h2>Competition Results</h2><p id="stats" class="muted">Loading results…</p><div id="results"></div><div class="actions"><button class="secondary" id="logout">Exit</button></div></div></div>`;document.querySelector("#logout").onclick=home;try{const snap=await getDocs(query(collection(db,"submissions"),orderBy("submittedAt","desc")));const rows=snap.docs.map(d=>d.data());document.querySelector("#stats").textContent=`${rows.length} submission(s) · Average: ${rows.length?(rows.reduce((a,r)=>a+(r.score||0),0)/rows.length).toFixed(1):"0"}/10`;document.querySelector("#results").innerHTML=rows.length?`<div style="overflow:auto"><table class="admin-table"><thead><tr><th>Student</th><th>ID</th><th>Score</th><th>Time</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.studentId)}</td><td><span class="pill">${r.score}/10</span></td><td>${esc(new Date(r.submittedAt).toLocaleString())}</td></tr>`).join("")}</tbody></table></div>`:"<p>No submissions yet.</p>"}catch(e){document.querySelector("#results").innerHTML='<div class="error">Could not load results. Make sure Firestore is enabled and its rules allow the admin read operation.</div>'}}
function showMsg(m,c){const el=document.querySelector("#msg");if(el)el.innerHTML=`<div class="${c}">${m}</div>`}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
home();